apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  namespace: expence-tracker-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo 
          image: mongo:latest
          ports:
           - containerPort: 27017
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          